### ISSUE TITLE
Bug with accented chars

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-ui#275]
Hi,

I noticed that I can't acknoledge a service when there are accented chars in the hostname. For example:
![image](https://user-images.githubusercontent.com/17827397/95218222-59816900-07f4-11eb-9525-caa37a678f56.png)

If I remove the accented chars, all works as expected!

**Comment by cgagnaire** [comment]
Hi,
Can you open an issue on the Centreon project https://github.com/centreon/centreon/issues ?
You will have to fill a template so we know what is your version, get some logs, etc.
Thanks!
